---

- name: Install docker
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"

- name: Start docker
  service: name=docker enabled=yes state=started

- meta: flush_handlers

- import_tasks: swarm.yml
  when: docker_swarm_create_cluster

- name: Create logrotate config for docker container logs
  template:
    src:   docker-container.logrotate.j2
    dest:  /etc/logrotate.d/docker-container-logs
    mode:  0644
  when: docker_container_logs_rotate

- name: add cron task for docker pruning
  cron:
    name: "docker pruning"
    minute: "10"
    hour: "2"
    job: "/usr/bin/docker system prune -f"
  tags: docker_prune